image: docker:latest

services:
- docker:dind

stages:
- test

before_script:
- docker info

test_suite:
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker run --rm $IMAGE_TAG npm run test
    - docker push $IMAGE_TAG
  tags:
  - docker